### ISSUE TITLE
EditText(@+id/EDView) loses focus after RecyclerView(@+id/RVContainer) gets new message from user or chagpt

### ISSUE THREAD

**Issue by vincentge** [nohjunh/ChatGPTAndroid#1]
Hi, Nohjunh, I want to say you really do a good  job, thanks for sharing such a good project!
I try to use this app, and input my openAI ai key, and it works, great!
But, I found that EditText(@+id/EDView) lost focus after RecyclerView(@+id/RVContainer) gets new message from user or chagpt, this stop me continuing to input text, I have to tap the EditText(@+id/EDView) once more to get the focus, so is there any way to slove this issue ?

**Comment by nohjunh** [comment]
Vincent, nice to meet you.
It was a sample for simple GPT linkage, so I didn't pay attention to detail implementation.
When new chats come and go, it seems to lose focus in the process of lowering scrollView (@+id/SVContainer).
How about simply using the requestFocus method?
I'll add a new commit.
