### ISSUE TITLE
There is issue in new version

### ISSUE THREAD

**Issue by InsertCart** [nohjunh/ChatGPTAndroid#3]
Now in chatgpt api has changed the return and this app crash while setting the return value, Also include GPT-3.5- turbo. Can you please check

**Comment by nohjunh** [comment]
hi,
If you modify the model to 'gpt-3.5-turbo-0301, does it crash?

**Comment by InsertCart** [comment]
> hi, Will there be a crash if you modify the model to 'gpt-3.5-turbo-0301'?

Yes, But I'm trying to modify code and adding AI Image search
